window.words12 = [
  "ABBREVIATION", "ACCELERATING", "ACCENTUATING", "ACCLIMATIZED", "ACCOMMODATED", "ACCOMPANYING", "ACCOMPLISHED", "ACCUMULATING", "ACCUMULATION", "ACKNOWLEDGING",
  "ACQUISITIONS", "ADAPTABILITY", "ADMINISTERED", "AGRICULTURAL", "ALTERNATIVES", "ANTICIPATING", "ANTICIPATION", "APPLICATIONS", "APPOINTMENTS", "APPRECIATING",
  "APPRECIATION", "ARCHITECTURE", "ARRANGEMENTS", "ARTICULATING", "ARTICULATION", "ASSOCIATIONS", "ASTRONOMICAL", "AUTHENTICITY", "AVAILABILITY", "BACKWARDNESS",
  "BENEFICIALLY", "BIOGRAPHICAL", "CANCELLATION", "CAPABILITIES", "CELEBRATIONS", "CERTIFICATES", "CIVILIZATION", "COMBINATIONS", "COMMEMORATED", "COMMEMORATES",
  "COMMENDATION", "COMMISSIONED", "COMMISSIONER", "COMMUNICATED", "COMMUNICATES", "COMPENSATION", "COMPETITIONS", "COMPILATIONS", "COMPLEMENTED", "COMPLICATING",
  "COMPLICATION", "COMPOSITIONS", "COMPREHENDED", "COMPROMISING", "COMPUTATIONS", "CONCENTRATED", "CONCENTRATES", "CONCEPTUALLY", "CONDITIONING", "CONFIDENTIAL",
  "CONFIRMATION", "CONNOTATIONS", "CONSEQUENCES", "CONSERVATIVE", "CONSERVATION", "CONSIDERABLE", "CONSIDERABLY", "CONSISTENTLY", "CONSOLIDATED", "CONSTITUENTS",
  "CONSTITUTION", "CONSTRUCTION", "CONTEMPORARY", "CONTINUATION", "CONTINUOUSLY", "CONTRIBUTING", "CONTRIBUTION", "CONTRIBUTORS", "CONVENTIONAL", "CONVERSATION",
  "COORDINATING", "COORDINATION", "COORDINATORS", "CORPORATIONS", "CORRESPONDED", "COUNTERPARTS", "CULTIVATIONS", "DECLARATIONS", "DECORATIVELY", "DEGENERATION",
  "DELIBERATELY", "DEMONSTRATED", "DEMONSTRATES", "DEPARTMENTAL", "DESCRIPTIONS", "DEVELOPMENTS", "DIFFERENTIAL", "DIFFICULTIES", "DISADVANTAGE", "DISAGREEMENT",
  "DISAPPEARING", "DISAPPOINTED", "DISCIPLINARY", "DISCONTINUED", "DISPLACEMENT", "DISTRIBUTION", "DISTRIBUTORS", "DUPLICATIONS", "ECONOMICALLY", "EFFICIENCIES",
  "ELECTRICALLY", "ELIMINATIONS", "EMANCIPATION", "EMBARRASSING", "ENCYCLOPEDIA", "ENLIGHTENING", "ENTERTAINERS", "ENTHUSIASTIC", "ENVIRONMENTS", "EQUIVALENTLY",
  "ESTABLISHING", "EVAPORATIONS", "EXAMINATIONS", "EXCLAMATIONS", "EXPECTATIONS", "EXPENDITURES", "EXPERIMENTAL", "EXPLANATIONS", "EXPLORATIONS", "FACILITATING",
  "FACILITATION", "FLUCTUATIONS", "FRUSTRATIONS", "FUNCTIONALLY", "GEOGRAPHICAL", "GOVERNMENTAL", "HEADQUARTERS", "HOSPITALIZED", "ILLUMINATING"
];